### ISSUE TITLE
Centos6.5 Build

### ISSUE THREAD

**Issue by scarywombat** [MaartenBaert/ssr#319]
Hello, I have tried following the Fedora instructions and the manual build instructions to get a SSR executable for Centos6.5, but I failed as this is using Qt4.6.*

Does anyone has detailed build instructions or a binary for Centos6.5

Regards.

**Comment by StripedMonkey** [comment]
In what way did it fail?

**Comment by scarywombat** [comment]
It failed to get past configuration due to the missing dependancy on Qt4.8, which does not seem to be available on Centos6.5

**Comment by MaartenBaert** [comment]
Qt 4.8 is a requirement, some features that I use are missing in older versions:
https://github.com/MaartenBaert/ssr/issues/153

I could work around these, but if you don't have Qt 4.8 then I doubt that you will have a version of ffmpeg/libav that is recent enough to work with SSR. The configure script can't detect libavcodec/libavformat versions, but anything older than those used by Ubuntu 12.04 will give compilation errors later on. And there's no easy way for me to work around those errors, because SSR depends heavily on those features.

**Comment by orodbhen** [comment]
I'm working on building this under CentOS 6.6 using conda. I'll let you know if I get it to work. It seems that you need a more recent version of gcc as well than is installed in CentOS 6, which means you may also need a more recent version of glibc.
